### ISSUE TITLE
npm i https://github.com/niklauslee/dht

### ISSUE THREAD

**Issue by okclover** [kaluma-project/kaluma-project.github.io#2]
# BEFORE PUBLISHING

Before publishing your package, please check `package.json` in your repository:
- [ ] `name` - Unique name in [Package Registry](https://kalumajs.org/packages/).
- [ ] `description` - A short single sentence description.
- [ ] `version` - Version number (semver format) (e.g. `1.0.0`)
- [ ] `main` - Entry point (e.g. `./index.js`)

---

# ENTER YOUR PACKAGE INFO

- Github URL : 
- name : 
- description :

**Comment by niklauslee** [comment]
@okclover Where is your package info?
