### ISSUE TITLE
[Publish Request] New Package

### ISSUE THREAD

**Issue by slashinfty** [kaluma-project/kaluma-project.github.io#7]
# ENTER YOUR PACKAGE INFO

- Github URL : https://github.com/slashinfty/i2c-lcd
- name : i2c-lcd
- description : Kaluma library for liquid crystal display with PCF8574 I2C port expander (LCM1602 module)

# CHECK BEFORE PUBLISHING

Before publishing your package, please check `package.json` in your repository:

- [x] `name` - Unique name in [Package Registry](https://kalumajs.org/packages/).
- [x] `description` - A short single sentence description.
- [x] `version` - Version number (semver format) (e.g. `1.0.0`)
- [x] `main` - Entry point (e.g. `./index.js`)

**Comment by niklauslee** [comment]
Done.
